//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using Cqrs.Repositories;
using Cqrs.Repositories.Queries;
using Northwind.Domain.Factories;
using Northwind.Domain.Orders.Repositories.Queries.Strategies;

namespace Northwind.Domain.Orders.Repositories
{
	[GeneratedCode("CQRS UML Code Generator", "1.500.0.1")]
	public partial interface IOrderRepository : IRepository<OrderQueryStrategy, Entities.OrderEntity>
	{
	}
}

namespace Northwind.Domain.Orders.Repositories.Queries.Strategies
{
	public partial class OrderQueryStrategy : QueryStrategy
	{
	}
}
