//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using MyCompany.MyProject.Domain.Authentication.Entities;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using System.Xml;
using Cqrs.Services;

namespace MyCompany.MyProject.Domain.Authentication.Services
{

	/// <summary>
	/// A <see cref="DataContractResolver"/> for using <see cref="IUserService.GetAll"/> via WCF
	/// </summary>
	[GeneratedCode("CQRS UML Code Generator", "1.601.786")]
	public partial class UserServiceGetAllResolver : ServiceParameterResolver<IUserService, Cqrs.Authentication.ISingleSignOnToken>
	{
		public UserServiceGetAllResolver(ISingleSignOnTokenResolver singleSignOnTokenResolver)
			: base(singleSignOnTokenResolver)
		{
		}

		public UserServiceGetAllResolver()
			: base(new Cqrs.Authentication.SingleSignOnTokenResolver())
		{
		}

		public override bool TryResolveType(Type dataContractType, Type declaredType, DataContractResolver knownTypeResolver, out XmlDictionaryString typeName, out XmlDictionaryString typeNamespace)
		{
			if (dataContractType == typeof(ServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, UserServiceGetAllParameters>))
			{
				XmlDictionary dictionary = new XmlDictionary();
				typeName = dictionary.Add("UserServiceGetAll");
				typeNamespace = dictionary.Add(ServiceNamespace);
				return true;
			}

			if (dataContractType == typeof(ServiceResponseWithResultData<IEnumerable<Entities.UserEntity>>))
			{
				XmlDictionary dictionary = new XmlDictionary();
				typeName = dictionary.Add("UserServiceGetAllResponse");
				typeNamespace = dictionary.Add(ServiceNamespace);
				return true;
			}

			return base.TryResolveType(dataContractType, declaredType, knownTypeResolver, out typeName, out typeNamespace);
		}

		protected override bool TryResolveUnResolvedType(Type dataContractType, Type declaredType, DataContractResolver knownTypeResolver, ref XmlDictionaryString typeName, ref XmlDictionaryString typeNamespace)
		{
			bool result = false;
			TryResolveUnResolvedType(dataContractType, declaredType, knownTypeResolver, ref typeName, ref typeNamespace, ref result);
			return result;
		}

		partial void TryResolveUnResolvedType(Type dataContractType, Type declaredType, DataContractResolver knownTypeResolver, ref XmlDictionaryString typeName, ref XmlDictionaryString typeNamespace, ref bool result);

		/// <summary>
		/// Override this method to map the specified xsi:type name and namespace to a data contract type during deserialization.
		/// </summary>
		/// <returns>
		/// The type the xsi:type name and namespace is mapped to. 
		/// </returns>
		/// <param name="typeName">The xsi:type name to map.</param><param name="typeNamespace">The xsi:type namespace to map.</param><param name="declaredType">The type declared in the data contract.</param><param name="knownTypeResolver">The known type resolver.</param>
		public override Type ResolveName(string typeName, string typeNamespace, Type declaredType, DataContractResolver knownTypeResolver)
		{
			if (typeNamespace == ServiceNamespace)
			{
				if (typeName == "UserServiceGetAll")
					return typeof(ServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, UserServiceGetAllParameters>);
			}

				if (typeName == "UserServiceGetAllResponse")
					return typeof(ServiceResponseWithResultData<IEnumerable<Entities.UserEntity>>);

			return base.ResolveName(typeName, typeNamespace, declaredType, knownTypeResolver);
		}

		protected override Type ResolveUnResolvedName(string typeName, string typeNamespace, Type declaredType, DataContractResolver knownTypeResolver)
		{
			Type result = null;
			ResolveUnResolvedName(typeName, typeNamespace, declaredType, knownTypeResolver, ref result);
			return result;
		}

		partial void ResolveUnResolvedName(string typeName, string typeNamespace, Type declaredType, DataContractResolver knownTypeResolver, ref Type result);

		public static void RegisterDataContracts()
		{
			WcfDataContractResolverConfiguration.Current.RegisterDataContract<IUserService, UserServiceGetAllResolver>("GetAll");
		}
	}


	/// <summary>
	/// A <see cref="DataContractResolver"/> for using <see cref="IUserService.GetByRsn"/> via WCF
	/// </summary>
	[GeneratedCode("CQRS UML Code Generator", "1.601.786")]
	public partial class UserServiceGetByRsnResolver : ServiceParameterResolver<IUserService, Cqrs.Authentication.ISingleSignOnToken>
	{
		public UserServiceGetByRsnResolver(ISingleSignOnTokenResolver singleSignOnTokenResolver)
			: base(singleSignOnTokenResolver)
		{
		}

		public UserServiceGetByRsnResolver()
			: base(new Cqrs.Authentication.SingleSignOnTokenResolver())
		{
		}

		public override bool TryResolveType(Type dataContractType, Type declaredType, DataContractResolver knownTypeResolver, out XmlDictionaryString typeName, out XmlDictionaryString typeNamespace)
		{
			if (dataContractType == typeof(ServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, UserServiceGetByRsnParameters>))
			{
				XmlDictionary dictionary = new XmlDictionary();
				typeName = dictionary.Add("UserServiceGetByRsn");
				typeNamespace = dictionary.Add(ServiceNamespace);
				return true;
			}

			if (dataContractType == typeof(ServiceResponseWithResultData<Entities.UserEntity>))
			{
				XmlDictionary dictionary = new XmlDictionary();
				typeName = dictionary.Add("UserServiceGetByRsnResponse");
				typeNamespace = dictionary.Add(ServiceNamespace);
				return true;
			}

			return base.TryResolveType(dataContractType, declaredType, knownTypeResolver, out typeName, out typeNamespace);
		}

		protected override bool TryResolveUnResolvedType(Type dataContractType, Type declaredType, DataContractResolver knownTypeResolver, ref XmlDictionaryString typeName, ref XmlDictionaryString typeNamespace)
		{
			bool result = false;
			TryResolveUnResolvedType(dataContractType, declaredType, knownTypeResolver, ref typeName, ref typeNamespace, ref result);
			return result;
		}

		partial void TryResolveUnResolvedType(Type dataContractType, Type declaredType, DataContractResolver knownTypeResolver, ref XmlDictionaryString typeName, ref XmlDictionaryString typeNamespace, ref bool result);

		/// <summary>
		/// Override this method to map the specified xsi:type name and namespace to a data contract type during deserialization.
		/// </summary>
		/// <returns>
		/// The type the xsi:type name and namespace is mapped to. 
		/// </returns>
		/// <param name="typeName">The xsi:type name to map.</param><param name="typeNamespace">The xsi:type namespace to map.</param><param name="declaredType">The type declared in the data contract.</param><param name="knownTypeResolver">The known type resolver.</param>
		public override Type ResolveName(string typeName, string typeNamespace, Type declaredType, DataContractResolver knownTypeResolver)
		{
			if (typeNamespace == ServiceNamespace)
			{
				if (typeName == "UserServiceGetByRsn")
					return typeof(ServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, UserServiceGetByRsnParameters>);
			}

				if (typeName == "UserServiceGetByRsnResponse")
					return typeof(ServiceResponseWithResultData<Entities.UserEntity>);

			return base.ResolveName(typeName, typeNamespace, declaredType, knownTypeResolver);
		}

		protected override Type ResolveUnResolvedName(string typeName, string typeNamespace, Type declaredType, DataContractResolver knownTypeResolver)
		{
			Type result = null;
			ResolveUnResolvedName(typeName, typeNamespace, declaredType, knownTypeResolver, ref result);
			return result;
		}

		partial void ResolveUnResolvedName(string typeName, string typeNamespace, Type declaredType, DataContractResolver knownTypeResolver, ref Type result);

		public static void RegisterDataContracts()
		{
			WcfDataContractResolverConfiguration.Current.RegisterDataContract<IUserService, UserServiceGetByRsnResolver>("GetByRsn");
		}
	}

}
