//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using MyCompany.MyProject.Domain.Terminals.Events;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Configuration;
using cdmdotnet.Logging;
using Cqrs.Snapshots;
using MyCompany.MyProject.Domain.Terminals.Events;

namespace MyCompany.MyProject.Domain.Terminals
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.786")]
	public  partial class Account : AggregateRoot<Cqrs.Authentication.ISingleSignOnToken>
	{
		public Guid Rsn
		{
			get { return Id; }
			private set { Id = value; }
		}

		public bool IsLogicallyDeleted {get; set;}

		#region Implementation of IMessageWithAuthenticationToken<Cqrs.Authentication.ISingleSignOnToken>

		public Cqrs.Authentication.ISingleSignOnToken AuthenticationToken { get; set; }

		#endregion

		protected IDependencyResolver DependencyResolver { get; private set; }

		protected ILogger Log { get; private set; }

		public double Balance { get; private set; }

// ReSharper disable UnusedMember.Local
		/// <summary>
		/// A constructor for the <see cref="Cqrs.Domain.Factories.IAggregateFactory"/>
		/// </summary>
		private Account()
		{

		}

		/// <summary>
		/// A constructor for the <see cref="Cqrs.Domain.Factories.IAggregateFactory"/>
		/// </summary>
		private Account(IDependencyResolver dependencyResolver, ILogger log)
		{
			DependencyResolver = dependencyResolver;
			Log = log;
		}
// ReSharper restore UnusedMember.Local

		public Account(IDependencyResolver dependencyResolver, ILogger log, Guid rsn)
		{
			DependencyResolver = dependencyResolver;
			Log = log;
			Rsn = rsn;
		}

		public void WithdrawFunds(double amount)
		{
			Log.LogDebug("Entered", "Account/WithdrawFunds");

			WithdrawFailedDueInsufficientFunds withdrawFailedDueInsufficientFundsEvent = null;
			WithdrawFundsFromAccountSucceeded withdrawFundsFromAccountSucceededEvent = null;

			OnWithdrawFunds(amount, ref withdrawFailedDueInsufficientFundsEvent, ref withdrawFundsFromAccountSucceededEvent);
			if (withdrawFailedDueInsufficientFundsEvent != null)
			{
				Log.LogDebug("Pre", "Account/WithdrawFunds/ApplyChange/WithdrawFailedDueInsufficientFunds");
				ApplyChange(withdrawFailedDueInsufficientFundsEvent);
				Log.LogDebug("Post", "Account/WithdrawFunds/ApplyChange/WithdrawFailedDueInsufficientFunds");
			}
			if (withdrawFundsFromAccountSucceededEvent != null)
			{
				Log.LogDebug("Pre", "Account/WithdrawFunds/ApplyChange/WithdrawFundsFromAccountSucceeded");
				ApplyChange(withdrawFundsFromAccountSucceededEvent);
				Log.LogDebug("Post", "Account/WithdrawFunds/ApplyChange/WithdrawFundsFromAccountSucceeded");
			}

			Log.LogDebug("Pre", "Account/WithdrawFunds/OnWithdrawFundsHandled");
			OnWithdrawFundsHandled(amount);
			Log.LogDebug("Post", "Account/WithdrawFunds/OnWithdrawFundsHandled");

			Log.LogDebug("Exited", "Account/WithdrawFunds");
		}

		partial void OnWithdrawFunds(double amount, ref WithdrawFailedDueInsufficientFunds withdrawFailedDueInsufficientFundsEvent, ref WithdrawFundsFromAccountSucceeded withdrawFundsFromAccountSucceededEvent);

		partial void OnWithdrawFundsHandled(double amount);


		public class AccountSnapshot : Snapshot
		{
			public bool IsLogicallyDeleted {get; set;}

			public double Balance { get; private set; }
		}
	}
}
