//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Cqrs.Events;
using Cqrs.Domain;

namespace MyCompany.MyProject.Domain.Terminals.Events.Handlers
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.786")]
	public  partial class WithdrawFundsFromAccountSucceededEventHandler
		
		: IEventHandler<Cqrs.Authentication.ISingleSignOnToken, WithdrawFundsFromAccountSucceeded>
	{

		#region Implementation of IEventHandler<in WithdrawFundsFromAccountSucceeded>

		public void Handle(WithdrawFundsFromAccountSucceeded @event)
		{
			OnHandle(@event);
		}

		#endregion

		partial void OnHandle(WithdrawFundsFromAccountSucceeded @event);
	}
}
