//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using System.CodeDom.Compiler;
using Cqrs.DataStores;

namespace MyCompany.MyProject.Domain.Factories
{
	[GeneratedCode("CQRS UML Code Generator", "1.500.497.383")]
	/// <summary>
	/// A factory for obtaining <see cref="IDataStore{TData}"/> instances
	/// </summary>
	public partial interface IDomainDataStoreFactory
	{
		IDataStore<Inventory.Entities.InventoryItemEntity> GetInventoryItemDataStore();

		IDataStore<Authentication.Entities.UserEntity> GetUserDataStore();

	}
}
