










//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using Northwind.Domain.Orders.Events;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;

using Cqrs.Services;
using Northwind.Domain.Orders.Services;

namespace Northwind.Domain.Orders.Services.ServiceHost.Ninject.ServiceChannelFactories
{

	/// <summary>
	/// A <see cref="ServiceChannelFactory{TService}"/> for using  <see cref="IOrderService.CreateOrder"/> via WCF
	/// </summary>
	public partial class HttpOrderServiceChannelFactory : ServiceChannelFactory<IOrderService>
	{
		/// <summary>
		/// Instantiates a new instance of the <see cref="HttpOrderServiceChannelFactory"/> class with the default endpoint configuration name of HttpOrderService.
		/// </summary>
		public HttpOrderServiceChannelFactory()
			: this("HttpOrderService")
		{
		}

		/// <summary>
		/// Instantiates a new instance of the <see cref="HttpOrderServiceChannelFactory"/> class with a specified endpoint configuration name.
		/// </summary>
		/// <param name="endpointConfigurationName">The configuration name used for the endpoint.</param>
		public HttpOrderServiceChannelFactory(string endpointConfigurationName)
			: base(endpointConfigurationName)
		{
		}

		protected override void RegisterDataContracts()
		{
			RegisterAggregateServiceDataContracts();
			RegisterServiceDataContracts();
		}

		partial void RegisterServiceDataContracts();
		partial void RegisterAggregateServiceDataContracts();
		partial void RegisterAggregateServiceDataContracts()
		{
	

			OrderServiceCreateOrderParametersResolver.RegisterDataContracts();


			OrderServiceUpdateOrderParametersResolver.RegisterDataContracts();


			OrderServiceDeleteOrderParametersResolver.RegisterDataContracts();

		}
	}
}
