<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<DebugType>full</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.23.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.1.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.0.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.2" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Cqrs.Azure.Functions.Isolated\Cqrs.Azure.Functions.Isolated.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="cqrs.settings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </None>
	</ItemGroup>

</Project>