//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Repositories;
using MyCompany.MyProject.Domain.Factories;
using MyCompany.MyProject.Domain.Terminals.Repositories.Queries.Strategies;

namespace MyCompany.MyProject.Domain.Terminals.Repositories
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.786")]
	public partial class AtmRepository : Repository<AtmQueryStrategy, AtmQueryStrategyBuilder, Entities.AtmEntity>, IAtmRepository
	{
		public AtmRepository(IDomainDataStoreFactory dataStoreFactory, AtmQueryStrategyBuilder atmQueryBuilder)
			: base(dataStoreFactory.GetAtmDataStore, atmQueryBuilder)
		{
		}
	}
}
