//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Configuration;
using Cqrs.Authentication;
using Cqrs.Repositories.Queries;
using Northwind.Domain.Factories;

namespace Northwind.Domain.Orders.Repositories.Queries.Strategies
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.881")]
	public partial class OrderQueryStrategyBuilder : QueryBuilder<OrderQueryStrategy, Entities.OrderEntity>, IOrderQueryStrategyBuilder
	{
		public OrderQueryStrategyBuilder(IDomainDataStoreFactory dataStoreFactory, IDependencyResolver dependencyResolver)
			: base(dataStoreFactory.GetOrderDataStore(), dependencyResolver)
		{
		}

		#region Overrides of QueryBuilder<OrderQueryStrategy,Entities.OrderEntity>

		protected override IQueryable<Entities.OrderEntity> GeneratePredicate(QueryPredicate queryPredicate, IQueryable<Entities.OrderEntity> leftHandQueryable = null)
		{
			OrderQueryStrategy queryStrategy = GetNullQueryStrategy();
			SortedSet<QueryParameter> parameters = queryPredicate.Parameters;

			IQueryable<Entities.OrderEntity> resultingQueryable = null;
			if (queryPredicate.Name == GetFunctionName<Guid>(queryStrategy.WithRsn))
			{
				OnGeneratePredicateWithRsn(queryPredicate, leftHandQueryable, parameters, ref resultingQueryable);
				GeneratePredicateWithRsn(parameters, leftHandQueryable, ref resultingQueryable);
				OnGeneratedPredicateWithRsn(queryPredicate, leftHandQueryable, parameters, ref resultingQueryable);
				return resultingQueryable;
			}
			if (queryPredicate.Name == GetFunctionName<int>(queryStrategy.WithOrderId))
			{
				OnGeneratePredicateWithOrderId(queryPredicate, leftHandQueryable, parameters, ref resultingQueryable);
				GeneratePredicateWithOrderId(parameters, leftHandQueryable, ref resultingQueryable);
				OnGeneratedPredicateWithOrderId(queryPredicate, leftHandQueryable, parameters, ref resultingQueryable);
				return resultingQueryable;
			}

			resultingQueryable
				= GeneratePredicateWithPermissionScopeAny<ISingleSignOnToken>(queryPredicate, leftHandQueryable)
				?? GeneratePredicateWithPermissionScopeUser<ISingleSignOnToken>(queryPredicate, leftHandQueryable)
				?? GeneratePredicateWithPermissionScopeCompany<ISingleSignOnToken>(queryPredicate, leftHandQueryable)
				?? GeneratePredicateWithPermissionScopeCompanyAndUser<ISingleSignOnToken>(queryPredicate, leftHandQueryable);

			if (resultingQueryable != null)
				return resultingQueryable;

			throw new InvalidOperationException("No known predicate could be generated.");
		}

		#endregion

		partial void OnGeneratePredicateWithRsn(QueryPredicate queryPredicate, IQueryable<Entities.OrderEntity> leftHandQueryable, SortedSet<QueryParameter> parameters, ref IQueryable<Entities.OrderEntity> resultingQueryable);

		partial void GeneratePredicateWithRsn(SortedSet<QueryParameter> parameters, IQueryable<Entities.OrderEntity> leftHandQueryable, ref IQueryable<Entities.OrderEntity> resultingQueryable);

		partial void OnGeneratedPredicateWithRsn(QueryPredicate queryPredicate, IQueryable<Entities.OrderEntity> leftHandQueryable, SortedSet<QueryParameter> parameters, ref IQueryable<Entities.OrderEntity> resultingQueryable);


		partial void OnGeneratePredicateWithOrderId(QueryPredicate queryPredicate, IQueryable<Entities.OrderEntity> leftHandQueryable, SortedSet<QueryParameter> parameters, ref IQueryable<Entities.OrderEntity> resultingQueryable);

		partial void GeneratePredicateWithOrderId(SortedSet<QueryParameter> parameters, IQueryable<Entities.OrderEntity> leftHandQueryable, ref IQueryable<Entities.OrderEntity> resultingQueryable);

		partial void OnGeneratedPredicateWithOrderId(QueryPredicate queryPredicate, IQueryable<Entities.OrderEntity> leftHandQueryable, SortedSet<QueryParameter> parameters, ref IQueryable<Entities.OrderEntity> resultingQueryable);


		protected override void ApplySorting(OrderQueryStrategy queryStrategy, ref IQueryable<Entities.OrderEntity> queryable)
		{
			var orderQueryable = (IOrderedQueryable<Entities.OrderEntity>)queryable;

			int index = 0;
			foreach (Func<int, OrderQueryStrategy> sortingMethod in queryStrategy.SortingList)
			{

			}
			queryable = orderQueryable;
		}

	}
}
