










//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;

using Cqrs.Services;
using MyCompany.MyProject.Domain.Authentication.Services;

namespace MyCompany.MyProject.Domain.Authentication.Services.ServiceHost.Ninject.ServiceChannelFactories
{

	/// <summary>
	/// A <see cref="ServiceChannelFactory{TService}"/> for using  <see cref="IUserService.CreateUser"/> via WCF
	/// </summary>
	public partial class HttpUserServiceChannelFactory : ServiceChannelFactory<IUserService>
	{
		/// <summary>
		/// Instantiates a new instance of the <see cref="HttpUserServiceChannelFactory"/> class with the default endpoint configuration name of HttpUserService.
		/// </summary>
		public HttpUserServiceChannelFactory()
			: this("HttpUserService")
		{
		}

		/// <summary>
		/// Instantiates a new instance of the <see cref="HttpUserServiceChannelFactory"/> class with a specified endpoint configuration name.
		/// </summary>
		/// <param name="endpointConfigurationName">The configuration name used for the endpoint.</param>
		public HttpUserServiceChannelFactory(string endpointConfigurationName)
			: base(endpointConfigurationName)
		{
		}

		protected override void RegisterDataContracts()
		{
			RegisterAggregateServiceDataContracts();
			RegisterServiceDataContracts();
		}

		partial void RegisterServiceDataContracts();
		partial void RegisterAggregateServiceDataContracts();
		partial void RegisterAggregateServiceDataContracts()
		{
	

			UserServiceCreateUserParametersResolver.RegisterDataContracts();


			UserServiceUpdateUserParametersResolver.RegisterDataContracts();


			UserServiceDeleteUserParametersResolver.RegisterDataContracts();

		}
	}
}
