//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Configuration;
using Cqrs.Authentication;
using Cqrs.Repositories.Queries;
using Northwind.Domain.Factories;

namespace Northwind.Domain.Orders.Repositories.Queries.Strategies
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.909")]
	public partial class InvoicesQueryStrategyBuilder : QueryBuilder<InvoicesQueryStrategy, Entities.InvoicesEntity>, IInvoicesQueryStrategyBuilder
	{
		public InvoicesQueryStrategyBuilder(IDomainDataStoreFactory dataStoreFactory, IDependencyResolver dependencyResolver)
			: base(dataStoreFactory.GetInvoicesDataStore(), dependencyResolver)
		{
		}

		#region Overrides of QueryBuilder<InvoicesQueryStrategy,Entities.InvoicesEntity>

		protected override IQueryable<Entities.InvoicesEntity> GeneratePredicate(QueryPredicate queryPredicate, IQueryable<Entities.InvoicesEntity> leftHandQueryable = null)
		{
			InvoicesQueryStrategy queryStrategy = GetNullQueryStrategy();
			SortedSet<QueryParameter> parameters = queryPredicate.Parameters;

			IQueryable<Entities.InvoicesEntity> resultingQueryable = null;
			if (queryPredicate.Name == GetFunctionName<Guid>(queryStrategy.WithRsn))
			{
				OnGeneratePredicateWithRsn(queryPredicate, leftHandQueryable, parameters, ref resultingQueryable);
				GeneratePredicateWithRsn(parameters, leftHandQueryable, ref resultingQueryable);
				OnGeneratedPredicateWithRsn(queryPredicate, leftHandQueryable, parameters, ref resultingQueryable);
				return resultingQueryable;
			}

			resultingQueryable
				= GeneratePredicateWithPermissionScopeAny<ISingleSignOnToken>(queryPredicate, leftHandQueryable)
				?? GeneratePredicateWithPermissionScopeUser<ISingleSignOnToken>(queryPredicate, leftHandQueryable)
				?? GeneratePredicateWithPermissionScopeCompany<ISingleSignOnToken>(queryPredicate, leftHandQueryable)
				?? GeneratePredicateWithPermissionScopeCompanyAndUser<ISingleSignOnToken>(queryPredicate, leftHandQueryable);

			if (resultingQueryable != null)
				return resultingQueryable;

			throw new InvalidOperationException("No known predicate could be generated.");
		}

		#endregion

		partial void OnGeneratePredicateWithRsn(QueryPredicate queryPredicate, IQueryable<Entities.InvoicesEntity> leftHandQueryable, SortedSet<QueryParameter> parameters, ref IQueryable<Entities.InvoicesEntity> resultingQueryable);

		partial void GeneratePredicateWithRsn(SortedSet<QueryParameter> parameters, IQueryable<Entities.InvoicesEntity> leftHandQueryable, ref IQueryable<Entities.InvoicesEntity> resultingQueryable);

		partial void OnGeneratedPredicateWithRsn(QueryPredicate queryPredicate, IQueryable<Entities.InvoicesEntity> leftHandQueryable, SortedSet<QueryParameter> parameters, ref IQueryable<Entities.InvoicesEntity> resultingQueryable);


		protected override void ApplySorting(InvoicesQueryStrategy queryStrategy, ref IQueryable<Entities.InvoicesEntity> queryable)
		{
			var orderQueryable = (IOrderedQueryable<Entities.InvoicesEntity>)queryable;

			int index = 0;
			foreach (Func<int, InvoicesQueryStrategy> sortingMethod in queryStrategy.SortingList)
			{

			}
			queryable = orderQueryable;
		}

	}
}
