//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using System.CodeDom.Compiler;
using cdmdotnet.Logging;
using Cqrs.Configuration;
using Cqrs.DataStores;

namespace Northwind.Domain.Factories
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.864")]
	/// <summary>
	/// A factory for obtaining <see cref="IDataStore{TData}"/> instances using the built-in simplified Sql
	/// </summary>
	public partial class DomainSimplifiedSqlDataStoreFactory : IDomainDataStoreFactory
	{
		public DomainSimplifiedSqlDataStoreFactory(ILogger logger, IConfigurationManager configurationManager)
		{
			Logger = logger;
			ConfigurationManager = configurationManager;
		}

		protected ILogger Logger { get; private set; }

		protected IConfigurationManager ConfigurationManager { get; private set; }

		#region Implementation of IDomainDataStoreFactory

		public virtual IDataStore<Orders.Entities.OrderEntity> GetOrderDataStore()
		{
			IDataStore<Orders.Entities.OrderEntity> result = new SqlDataStore<Orders.Entities.OrderEntity>(ConfigurationManager, Logger);
			OnGetOrderDataStore(ref result);
			return result;
		}

		public virtual IDataStore<Orders.Entities.InvoicesEntity> GetInvoicesDataStore()
		{
			IDataStore<Orders.Entities.InvoicesEntity> result = new SqlDataStore<Orders.Entities.InvoicesEntity>(ConfigurationManager, Logger);
			OnGetInvoicesDataStore(ref result);
			return result;
		}


		#endregion

		partial void OnGetOrderDataStore(ref IDataStore<Orders.Entities.OrderEntity> result);

		partial void OnGetInvoicesDataStore(ref IDataStore<Orders.Entities.InvoicesEntity> result);

	}
}
