//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using MyCompany.MyProject.Domain.Authentication.Entities;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Authentication;
using Cqrs.Services;

namespace MyCompany.MyProject.Domain.Authentication.Services
{
	public partial interface IUserService 
	{
		[OperationContract]
		IServiceResponseWithResultData<IEnumerable<Entities.UserEntity>> GetAll(IServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, UserServiceGetAllParameters> serviceRequest);

		[OperationContract]
		IServiceResponseWithResultData<Entities.UserEntity> GetByRsn(IServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, UserServiceGetByRsnParameters> serviceRequest);

	}

	/// <summary>
	/// The parameters for the <see cref="IUserService.GetAll" /> method.
	/// </summary>
	public class UserServiceGetAllParameters
	{
	}

	/// <summary>
	/// The parameters for the <see cref="IUserService.GetByRsn" /> method.
	/// </summary>
	public class UserServiceGetByRsnParameters
	{
		public Guid rsn { get; set; }

	}

}
