//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using MyCompany.MyProject.Domain.Inventory.Entities;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Authentication;
using Cqrs.Services;

namespace MyCompany.MyProject.Domain.Inventory.Services
{
	public partial interface IInventoryItemService 
	{
		[OperationContract]
		IServiceResponseWithResultData<IEnumerable<Entities.InventoryItemSummaryEntity>> GetAll(IServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, InventoryItemServiceGetAllParameters> serviceRequest);

		[OperationContract]
		IServiceResponseWithResultData<Entities.InventoryItemEntity> GetByRsn(IServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, InventoryItemServiceGetByRsnParameters> serviceRequest);

		[OperationContract]
		IServiceResponse ChangeName(IServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, InventoryItemServiceChangeNameParameters> serviceRequest);

		[OperationContract]
		IServiceResponse CheckIn(IServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, InventoryItemServiceCheckInParameters> serviceRequest);

		[OperationContract]
		IServiceResponse Create(IServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, InventoryItemServiceCreateParameters> serviceRequest);

		[OperationContract]
		IServiceResponse Deactivate(IServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, InventoryItemServiceDeactivateParameters> serviceRequest);

		[OperationContract]
		IServiceResponse Remove(IServiceRequestWithData<Cqrs.Authentication.ISingleSignOnToken, InventoryItemServiceRemoveParameters> serviceRequest);

	}

	/// <summary>
	/// The parameters for the <see cref="IInventoryItemService.GetAll" /> method.
	/// </summary>
	public class InventoryItemServiceGetAllParameters
	{
	}

	/// <summary>
	/// The parameters for the <see cref="IInventoryItemService.GetByRsn" /> method.
	/// </summary>
	public class InventoryItemServiceGetByRsnParameters
	{
		public Guid rsn { get; set; }

	}

	/// <summary>
	/// The parameters for the <see cref="IInventoryItemService.ChangeName" /> method.
	/// </summary>
	public class InventoryItemServiceChangeNameParameters
	{
		public Guid rsn { get; set; }

		public string newName { get; set; }

	}

	/// <summary>
	/// The parameters for the <see cref="IInventoryItemService.CheckIn" /> method.
	/// </summary>
	public class InventoryItemServiceCheckInParameters
	{
		public Guid rsn { get; set; }

		public long count { get; set; }

	}

	/// <summary>
	/// The parameters for the <see cref="IInventoryItemService.Create" /> method.
	/// </summary>
	public class InventoryItemServiceCreateParameters
	{
		public string name { get; set; }

	}

	/// <summary>
	/// The parameters for the <see cref="IInventoryItemService.Deactivate" /> method.
	/// </summary>
	public class InventoryItemServiceDeactivateParameters
	{
		public Guid rsn { get; set; }

	}

	/// <summary>
	/// The parameters for the <see cref="IInventoryItemService.Remove" /> method.
	/// </summary>
	public class InventoryItemServiceRemoveParameters
	{
		public Guid rsn { get; set; }

		public long count { get; set; }

	}

}
