//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Authentication;
using Cqrs.Repositories.Queries;

namespace MyCompany.MyProject.Domain.Authentication.Repositories.Queries.Strategies
{
	[GeneratedCode("CQRS UML Code Generator", "1.500.480.367")]
	public partial class UserQueryStrategy : QueryStrategy, IUserQueryStrategy
	{
		protected IAuthenticationTokenHelper<System.Guid> AuthenticationTokenHelper { get; private set; }

		internal IList<Func<int, UserQueryStrategy>> SortingList { get; set; }

		public UserQueryStrategy(IAuthenticationTokenHelper<System.Guid> authenticationTokenHelper)
		{
			AuthenticationTokenHelper = authenticationTokenHelper;
			SortingList = new List<Func<int, UserQueryStrategy>>();
		}

	}
}
