










//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using MyCompany.MyProject.Domain.Inventory.Entities;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;

using Cqrs.Services;

namespace MyCompany.MyProject.Domain.Inventory.Services.ServiceHost.Ninject.ServiceChannelFactories
{
	/// <summary>
	/// A <see cref="ServiceChannelFactory{TService}"/> for using  <see cref="IInventoryItemService"/> via WCF
	/// </summary>
	[GeneratedCode("CQRS UML Code Generator", "1.601.786")]
	public partial class HttpInventoryItemServiceChannelFactory : ServiceChannelFactory<IInventoryItemService>
	{

		partial void RegisterServiceDataContracts()
		{

			InventoryItemServiceGetAllResolver.RegisterDataContracts();

			InventoryItemServiceGetByRsnResolver.RegisterDataContracts();

			InventoryItemServiceChangeNameResolver.RegisterDataContracts();

			InventoryItemServiceCheckInResolver.RegisterDataContracts();

			InventoryItemServiceCreateResolver.RegisterDataContracts();

			InventoryItemServiceDeactivateResolver.RegisterDataContracts();

			InventoryItemServiceRemoveResolver.RegisterDataContracts();

		}
	}
}
