//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;

namespace MyCompany.MyProject.Domain.Authentication
{
	[GeneratedCode("CQRS UML Code Generator", "1.500.497.383")]
	public  partial interface IUserEntity
	{
		[DataMember]
		string Name { get; set; }

		[DataMember]
		Guid Rsn { get; set; }

	}
}
