//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Entities;

namespace Northwind.Domain.Orders.Entities
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.881")]
	public  partial interface IInvoicesEntity : IEntity
	{
		[DataMember]
		string ShipName { get; set; }

		[DataMember]
		string ShipAddress { get; set; }

		[DataMember]
		string ShipCity { get; set; }

		[DataMember]
		string ShipRegion { get; set; }

		[DataMember]
		string ShipPostalCode { get; set; }

		[DataMember]
		string ShipCountry { get; set; }

		[DataMember]
		int CustomerId { get; set; }

		[DataMember]
		string CompanyName { get; set; }

		[DataMember]
		string Address { get; set; }

		[DataMember]
		string City { get; set; }

		[DataMember]
		string Region { get; set; }

		[DataMember]
		string PostalCode { get; set; }

		[DataMember]
		string Country { get; set; }

		[DataMember]
		string Salesperson { get; set; }

		[DataMember]
		int OrderId { get; set; }

		[DataMember]
		DateTime OrderDate { get; set; }

		[DataMember]
		DateTime RequiredDate { get; set; }

		[DataMember]
		DateTime ShippedDate { get; set; }

		[DataMember]
		string ShipperName { get; set; }

		[DataMember]
		int ProductId { get; set; }

		[DataMember]
		string ProductName { get; set; }

		[DataMember]
		double UnitPrice { get; set; }

		[DataMember]
		int Quantity { get; set; }

		[DataMember]
		double Discount { get; set; }

		[DataMember]
		double ExtendedPrice { get; set; }

		[DataMember]
		double Freight { get; set; }

	}
}
