//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Cqrs.Commands;
using Cqrs.Configuration;
using Cqrs.Domain;
using Cqrs.Logging;

namespace MyCompany.MyProject.Domain.Inventory.Commands.Handlers
{
	[GeneratedCode("CQRS UML Code Generator", "1.500.497.383")]
	public  partial class RenameInventoryItemCommandHandler : ICommandHandler<System.Guid, RenameInventoryItemCommand>
	{
		protected IUnitOfWork<System.Guid> UnitOfWork { get; private set; }

		protected IDependencyResolver DependencyResolver { get; private set; }

		protected ILog Log { get; private set; }

		public RenameInventoryItemCommandHandler(IUnitOfWork<System.Guid> unitOfWork, IDependencyResolver dependencyResolver, ILog log)
		{
			UnitOfWork = unitOfWork;
			DependencyResolver = dependencyResolver;
			Log = log;
		}

		public string NewName { get; set; }


		#region Implementation of ICommandHandler<in RenameInventoryItem>

		public void Handle(RenameInventoryItemCommand command)
		{
			OnHandle(command);
		}

		#endregion
		partial void OnHandle(RenameInventoryItemCommand command);

	}
}
