//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using System.CodeDom.Compiler;
using Cqrs.DataStores;
using cdmdotnet.Logging;

namespace MyCompany.MyProject.Domain.Factories
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.786")]
	/// <summary>
	/// A factory for obtaining <see cref="IDataStore{TData}"/> instances using an InProcess only approach
	/// </summary>
	public partial class DomainInProcessDataStoreFactory : IDomainDataStoreFactory
	{
		#region Implementation of IDomainDataStoreFactory

		#endregion

	}
}
