name: Build Core Framework

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
    - uses: actions/checkout@v1
    - name: Setup dotnet CLI
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.0.100
    - name: Prepare Legacy NuGet
      run: |
        cd .\.nuget
        ren NuGet.ex_ NuGet.exe
        cd ..
        .nuget\NuGet.exe restore Cqrs.sln
    - name: Build with dotnet CLI
      run: dotnet build --configuration Release .\Cqrs.sln
