//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using Cqrs.Commands;
using Cqrs.Authentication;
using Cqrs.Logging;
using Cqrs.Repositories.Queries;
using Cqrs.Services;
using MyCompany.MyProject.Domain.Inventory.Commands;
using MyCompany.MyProject.Domain.Inventory.Repositories;

namespace MyCompany.MyProject.Domain.Inventory.Services
{
	[GeneratedCode("CQRS UML Code Generator", "1.500.508.396")]
	[DataContract(Namespace="http://www.cdmdotnet.com/MyProject/Domain/Inventory/1001/")]
	public partial class InventoryItemService : IInventoryItemService
	{
		protected ICommandSender<Cqrs.Authentication.ISingleSignOnToken> CommandSender { get; private set; }

		protected IUnitOfWorkService UnitOfWorkService { get; private set; }

		protected IInventoryItemRepository InventoryItemRepository { get; private set; }

		protected IQueryFactory QueryFactory { get; private set; }

		protected IAuthenticationTokenHelper<Cqrs.Authentication.ISingleSignOnToken> AuthenticationTokenHelper { get; set; }

		protected ICorrolationIdHelper CorrolationIdHelper { get; set; }

		public InventoryItemService(ICommandSender<Cqrs.Authentication.ISingleSignOnToken> commandSender, IUnitOfWorkService unitOfWorkService, IQueryFactory queryFactory, IAuthenticationTokenHelper<Cqrs.Authentication.ISingleSignOnToken> authenticationTokenHelper, ICorrolationIdHelper corrolationIdHelper, IInventoryItemRepository inventoryItemRepository)
		{
			CommandSender = commandSender;
			UnitOfWorkService = unitOfWorkService;
			QueryFactory = queryFactory;
			AuthenticationTokenHelper = authenticationTokenHelper;
			CorrolationIdHelper = corrolationIdHelper;
			InventoryItemRepository = inventoryItemRepository;
		}


		protected virtual TServiceResponse CompleteResponse<TServiceResponse>(TServiceResponse serviceResponse)
			where TServiceResponse : IServiceResponse
		{
			serviceResponse.CorrolationId = CorrolationIdHelper.GetCorrolationId();
			return serviceResponse;
		}
	}
}
